
###########################################redis cluster 配置###############################################
gznb:
 redis:
   cluster:
     nodes[0]: 10.66.2.90:6379
     nodes[1]: 10.66.2.90:6380
     nodes[2]: 10.66.2.90:6381
     nodes[3]: 10.66.2.90:6479
     nodes[4]: 10.66.2.90:6480
     nodes[5]: 10.66.2.90:6481
     connectionTimeout: 3000
     soTimeout: 5000
     maxAttempts: 5
   pool:
     #可用连接实例的最大数目，默认值为8
     #如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
     maxTotal: 1000
     #控制一个pool最多有多少个状态为idle(空闲的)的jedis实例，默认值也是8
     maxIdle: 200
     #等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
     maxWaitMillis: 2000
     #在borrow一个jedis实例时，是否提前进行validate操作；如果为true，则得到的jedis实例均是可用的
     testOnBorrow: true
     #在return给pool时，是否提前进行validate操作
     testOnReturn: true


